service: my-sls-lambda
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-1

custom:
  fileUploadBucketName: ${self:service}-bucket-${self:provider.stage}

functions:
  generateRandomNumber:
    handler: src/handler.generateRandomNumber
    timeout: 60 #secondes
    memorySize: 128 # mb


resources:
  Resources:
    FileBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.fileUploadBucketName}
        AccessControl: PublicRead
        