service: serverless-lambda-test
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-1

functions:
  generateRandomNumber:
    handler: src/handler.generateRandomNumber
    timeout: 60 #secondes
    memorySize: 128 # mb
